[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # ADD THIS LINE:
  external_node_modules = ["express", "cors", "inngest", "mongoose", "serverless-http", "stream-chat"]

[[plugins]]
  package = "netlify-plugin-inngest"

[[redirects]]
  from = "/api/inngest"
  to = "/.netlify/functions/inngest"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200