[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Rule 1: Send Inngest traffic to the standalone Inngest function
[[redirects]]
  from = "/api/inngest"
  to = "/.netlify/functions/inngest"
  status = 200

# Rule 2: Send ALL OTHER API traffic to your Express App (api.js)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200